# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"{\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x04 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x05 \x01(\t\"$\n\x11InitOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xa2\x01\n\x10UserFraudRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12H\n\x0cvector_clock\x18\x02 \x03(\x0b\x32\x32.fraud_detection.UserFraudRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xa2\x01\n\x10\x43\x61rdFraudRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12H\n\x0cvector_clock\x18\x02 \x03(\x0b\x32\x32.fraud_detection.CardFraudRequest.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xb6\x01\n\x12\x46raudEventResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12J\n\x0cvector_clock\x18\x03 \x03(\x0b\x32\x34.fraud_detection.FraudEventResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xa5\x02\n\x15\x46raudDetectionService\x12R\n\tInitOrder\x12!.fraud_detection.InitOrderRequest\x1a\".fraud_detection.InitOrderResponse\x12X\n\x0e\x43heckUserFraud\x12!.fraud_detection.UserFraudRequest\x1a#.fraud_detection.FraudEventResponse\x12^\n\x14\x43heckCreditCardFraud\x12!.fraud_detection.CardFraudRequest\x1a#.fraud_detection.FraudEventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERFRAUDREQUEST_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_USERFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_CARDFRAUDREQUEST_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_CARDFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_FRAUDEVENTRESPONSE_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_FRAUDEVENTRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_INITORDERREQUEST']._serialized_start=42
  _globals['_INITORDERREQUEST']._serialized_end=165
  _globals['_INITORDERRESPONSE']._serialized_start=167
  _globals['_INITORDERRESPONSE']._serialized_end=203
  _globals['_USERFRAUDREQUEST']._serialized_start=206
  _globals['_USERFRAUDREQUEST']._serialized_end=368
  _globals['_USERFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_start=318
  _globals['_USERFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_end=368
  _globals['_CARDFRAUDREQUEST']._serialized_start=371
  _globals['_CARDFRAUDREQUEST']._serialized_end=533
  _globals['_CARDFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_start=318
  _globals['_CARDFRAUDREQUEST_VECTORCLOCKENTRY']._serialized_end=368
  _globals['_FRAUDEVENTRESPONSE']._serialized_start=536
  _globals['_FRAUDEVENTRESPONSE']._serialized_end=718
  _globals['_FRAUDEVENTRESPONSE_VECTORCLOCKENTRY']._serialized_start=318
  _globals['_FRAUDEVENTRESPONSE_VECTORCLOCKENTRY']._serialized_end=368
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=721
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=1014
# @@protoc_insertion_point(module_scope)
