# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"=\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\"D\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x18\n\x10\x65xpected_version\x18\x03 \x01(\x03\"@\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xb3\x01\n\rBooksDatabase\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12&\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12(\n\tLocalRead\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12+\n\nLocalWrite\x12\r.WriteRequest\x1a\x0e.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=18
  _globals['_READREQUEST']._serialized_end=44
  _globals['_READRESPONSE']._serialized_start=46
  _globals['_READRESPONSE']._serialized_end=107
  _globals['_WRITEREQUEST']._serialized_start=109
  _globals['_WRITEREQUEST']._serialized_end=177
  _globals['_WRITERESPONSE']._serialized_start=179
  _globals['_WRITERESPONSE']._serialized_end=243
  _globals['_BOOKSDATABASE']._serialized_start=246
  _globals['_BOOKSDATABASE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
