# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"#\n\x12VerifyItemsRequest\x12\r\n\x05items\x18\x01 \x03(\t\"\x81\x01\n\x15VerifyUserDataRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0b\n\x03zip\x18\x06 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x07 \x01(\t\"O\n\x17VerifyCreditCardRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"2\n\x0eVerifyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\xe5\x02\n\x1eTransactionVerificationService\x12\x65\n\x0bVerifyItems\x12,.transaction_verification.VerifyItemsRequest\x1a(.transaction_verification.VerifyResponse\x12k\n\x0eVerifyUserData\x12/.transaction_verification.VerifyUserDataRequest\x1a(.transaction_verification.VerifyResponse\x12o\n\x10VerifyCreditCard\x12\x31.transaction_verification.VerifyCreditCardRequest\x1a(.transaction_verification.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYITEMSREQUEST']._serialized_start=60
  _globals['_VERIFYITEMSREQUEST']._serialized_end=95
  _globals['_VERIFYUSERDATAREQUEST']._serialized_start=98
  _globals['_VERIFYUSERDATAREQUEST']._serialized_end=227
  _globals['_VERIFYCREDITCARDREQUEST']._serialized_start=229
  _globals['_VERIFYCREDITCARDREQUEST']._serialized_end=308
  _globals['_VERIFYRESPONSE']._serialized_start=310
  _globals['_VERIFYRESPONSE']._serialized_end=360
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=363
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
