# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"&\n\x0f\x45lectionRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\"3\n\x10\x45lectionResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\x12\n\n\x02ok\x18\x02 \x01(\x08\")\n\x12\x43oordinatorRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\"@\n\x13\x43oordinatorResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63knowledged\x18\x02 \x01(\x08\"\'\n\x10HeartbeatRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\"7\n\x11HeartbeatResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\x12\r\n\x05\x61live\x18\x02 \x01(\x08\x32\x88\x02\n\rOrderExecutor\x12M\n\x08\x45lection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12V\n\x0b\x43oordinator\x12\".order_executor.CoordinatorRequest\x1a#.order_executor.CoordinatorResponse\x12P\n\tHeartbeat\x12 .order_executor.HeartbeatRequest\x1a!.order_executor.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=40
  _globals['_ELECTIONREQUEST']._serialized_end=78
  _globals['_ELECTIONRESPONSE']._serialized_start=80
  _globals['_ELECTIONRESPONSE']._serialized_end=131
  _globals['_COORDINATORREQUEST']._serialized_start=133
  _globals['_COORDINATORREQUEST']._serialized_end=174
  _globals['_COORDINATORRESPONSE']._serialized_start=176
  _globals['_COORDINATORRESPONSE']._serialized_end=240
  _globals['_HEARTBEATREQUEST']._serialized_start=242
  _globals['_HEARTBEATREQUEST']._serialized_end=281
  _globals['_HEARTBEATRESPONSE']._serialized_start=283
  _globals['_HEARTBEATRESPONSE']._serialized_end=338
  _globals['_ORDEREXECUTOR']._serialized_start=341
  _globals['_ORDEREXECUTOR']._serialized_end=605
# @@protoc_insertion_point(module_scope)
